__author__ = 'penglong_feng'
CSRF_ENABLED = True
SECRET_KEY = 'xt-erpcloud.kingdee.com'


#mongo setting
MONGO_HOST='192.168.22.198'
MONGO_PORT='27017'
MONGO_DBNAME='paylm'
#  PREFIX_AUTO_START_REQUEST, PREFIX_REPLICA_SET, PREFIX_READ_PREFERENCE, PREFIX_USERNAM